#!/bin/sh
#Tomcat starting script
#
#chkconfig: 345 90 10
#description: tomcat
#prcocessname: tomcat7

CATALINA_HOME=#catalina_home#


case $1 in
        start)
                echo "Starting tomcat 7"
                sh $CATALINA_HOME/bin/startup.sh >/dev/null 2>&1
                ;;
        stop)
                echo "Stopping tomcat 7"
                sh $CATALINA_HOME/bin/shutdown.sh >/dev/null 2>&1
                ;;
        *)
                # usage
                echo "Usage: $0 start|stop"
                ;;
esac
